In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import os

In [3]:
path = "C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)"

path_all = ["C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\" 
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G15\\"
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G17\\"
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G19\\"
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G32\\"
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G34\\"
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G48\\"
            ,"C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G49\\"]

files_all = []
path_a = []
files = os.listdir(path)
for i in range(len(path_all)):
    files_all.append(os.listdir(path_all[i]))
    for a in range(len(files_all[i])):
        path_a.append(path_all[i] + files_all[i][a])
path_a

['C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160126-002Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160311-003_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160428-002_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160509-001_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160511-002_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160517-002_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7x15)20160518-004_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160526-003_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7x15)20160531-002_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160602-001_Export.txt',
 'C:\\Users\\pc\\Desktop\\大數據競賽初賽資料(230測試數據)\\G11\\G11-1-AC(7X15)20160604-001_Export.txt',


In [4]:
df_values = []
df = []
csv=[]
for i in range(len(path_a)):
    
    df_values.append(np.float64(pd.read_table(path_a[i]).iloc[1:,:-1].T))
    
    
    df.append(pd.read_table(path_a[i]).iloc[1:,:-1])
    df[i] = df[i].astype(float)
    
    
    csv.append(pd.DataFrame(df[i]))

C:\Users\pc\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  
C:\Users\pc\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  if __name__ == '__main__':


In [5]:
len(files_all[0])

23

In [6]:
for i in range(len(files_all)):
    for t in range(len(files_all[i])):
        csv[i].to_csv(r'C:\Users\pc\Desktop\2019_csv\%s.csv'% files_all[i][t][:-4])

In [7]:
df_values

[array([[ 65.9,  65.9,  65.9, ..., 127.2, 125.7, 125.3],
        [ 65.8,  65.8,  65.8, ..., 112.9, 111.3, 110.7],
        [ 64.2,  64.2,  64.2, ..., 111.1, 109.6, 109.3],
        [ 64.9,  64.9,  64.9, ..., 139.6, 138.1, 137.5],
        [ 66. ,  66. ,  66. , ..., 123. , 122. , 121.8]]),
 array([[ 64.9,  64.9,  64.9, ..., 120.3, 118.6, 118.5],
        [ 65.2,  65.2,  65.2, ..., 139.3, 137.9, 137.6],
        [ 65.3,  65.3,  65.3, ..., 129.7, 128.9, 128.9],
        [ 65.2,  65.2,  65.2, ..., 123.1, 121.9, 121.8],
        [ 65. ,  65. ,  65. , ..., 119.6, 118.3, 118.1],
        [ 64.3,  64.3,  64.3, ..., 118.3, 117.6, 117.4]]),
 array([[ 75.3,  75.3,  75.3, ..., 117.6, 115.4, 114.8],
        [ 75.1,  75.1,  75.1, ..., 118. , 116.1, 115.3],
        [ 75.8,  75.8,  75.8, ..., 125.6, 123.4, 122.4],
        [ 76.6,  76.6,  76.6, ..., 138.6, 137. , 136. ],
        [ 76. ,  76. ,  76. , ..., 128.5, 126.6, 125.7],
        [ 75.1,  75.1,  75.1, ..., 128.8, 127.3, 126.6]]),
 array([[ 81.5,  81.5,  8

In [8]:
from statsmodels.tsa.ar_model import AR
from random import random

In [9]:
# fit model
for m in range(10):
    for i in range(5):
        for data in [df_values[0][i]]:
            model = AR(data)
            model_fit = model.fit()
        # make prediction
            print('Lag: %s' % model_fit.k_ar)
            print('Coefficients: %s' % model_fit.params)

Lag: 15
Coefficients: [ 0.17820172  1.62242249 -0.53174223  0.05795455 -0.02998127 -0.08084953
 -0.0158978  -0.01027147  0.14238913 -0.28913581  0.17851819 -0.0878108
 -0.0794287   0.18964633 -0.10536714  0.03887099]
Lag: 15
Coefficients: [ 0.2700541   1.38522413 -0.02608024 -0.34961511  0.16100036 -0.07127634
 -0.16695036  0.14489606  0.03632797 -0.19361993  0.07080372 -0.05464172
 -0.00170713  0.14960908 -0.12993982  0.04490335]
Lag: 15
Coefficients: [ 0.22987822  1.49390419 -0.21208428 -0.10276695 -0.28392082  0.32698638
 -0.32974669  0.15569264 -0.00351327 -0.07417934  0.05751367  0.00340357
 -0.14662136  0.14267817 -0.05916689  0.03091788]
Lag: 15
Coefficients: [ 0.2103593   1.51667631 -0.36125853  0.09621787 -0.3208546   0.28167542
 -0.13461028 -0.10383977  0.03057531  0.00378465 -0.107059    0.13754331
 -0.02812223 -0.04022468 -0.05438923  0.0831216 ]
Lag: 15
Coefficients: [ 0.27657377  1.49342568 -0.26790755 -0.0805864  -0.18586194  0.2580148
 -0.25239906  0.09180106  0.0794427